secretsprovider: awskms://alias/ltbase-pulumi-secrets?region=us-east-2
encryptedkey: AQICAHiP1KlI+KUDwO1vCo1Jgg1zjwRV/0fA7buos2m9RV+3tAHmz9fH7dsrM/Fbt+m+Y0cxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPIykend+2/sUhCS3AgEQgDs93+t5bHL75f4J8nsLxt0f+JKqtMVLG35C8LJQbGfjwK+eY53NafTo7MCg0+XKnoSkKflpTXHEyYx1rg==
config:
  ltbase-infra:awsRegion: us-east-2
  ltbase-infra:runtimeBucket: ltbase-private-deployment-demo01-runtime-devo
  ltbase-infra:tableName: ltbase-private-deployment-demo01-devo
  ltbase-infra:mtlsTruststoreFile: infra/certs/cloudflare-origin-pull-ca.pem
  ltbase-infra:mtlsTruststoreKey: mtls/cloudflare-origin-pull-ca.pem
  ltbase-infra:apiDomain: demo01-api-devo.ltbase.dev
  ltbase-infra:controlPlaneDomain: demo01-ctl-devo.ltbase.dev
  ltbase-infra:authDomain: demo01-auth-devo.ltbase.dev
  ltbase-infra:cloudflareZoneId: b4ba9f847e6e12a0abb4d3d1f52bb752
  ltbase-infra:oidcIssuerUrl: https://ltbase-demo01-oidc.ltbase.dev/devo
  ltbase-infra:jwksUrl: https://ltbase-demo01-oidc.ltbase.dev/devo/.well-known/jwks.json
  ltbase-infra:githubOrg: iceboundrock
  ltbase-infra:githubRepo: ltbase-private-deployment-demo01
  ltbase-infra:releaseId: v1.0.0
  ltbase-infra:dsqlPort: "5432"
  ltbase-infra:dsqlDB: postgres
  ltbase-infra:dsqlUser: admin
  ltbase-infra:dsqlProjectSchema: ltbase
  ltbase-infra:geminiModel: gemini-3-flash-preview
  ltbase-infra:geminiApiKey:
    secure: v1:zwBxzNUM/rPEX2v1:p6DE4wFGbAMZYCFGuSQxvC1LMSGp7Pji3uIkho75zJIRHUGLjetT74NbVzi7KDayL9IRMMYeGg==
  ltbase-infra:githubOidcProviderArn: arn:aws:iam::009853298710:oidc-provider/token.actions.githubusercontent.com
  ltbase-infra:deploymentAwsAccountId: "009853298710"
  ltbase-infra:projectId: d6ca77fc-176e-4ba8-8a5a-68ce81d3c7bd
  ltbase-infra:authProviderConfigFile: infra/auth-providers.devo.json
  ltbase-infra:schemaBucket: ltbase-private-deployment-demo01-schema-devo
